# aset = set('abc')
# bset = set('bcd')
# print(len(aset))
# for ch in aset:
#     print(ch)
# print(aset & bset)
# print(aset | bset)
# print(aset - bset)
cset = set('hello')
print(cset)
cset.add('new')
print(cset)
